# Generated by Django 4.1.4 on 2022-12-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='Item Title', max_length=100),
        ),
    ]
